 export const originalDeck = [
  {id: 'c1', value: 1, suit: 'club', src: './Images/Cards/c1.jpg'},
  {id: 'c2', value: 2, suit: 'club', src: './Images/Cards/c2.jpg'},
  {id: 'c3', value: 3, suit: 'club', src: './Images/Cards/c3.jpg'},
  {id: 'c4', value: 4, suit: 'club', src: './Images/Cards/c4.jpg'},
  {id: 'c5', value: 5, suit: 'club', src: './Images/Cards/c5.jpg'},
  {id: 'c6', value: 6, suit: 'club', src: './Images/Cards/c6.jpg'},
  {id: 'c7', value: 7, suit: 'club', src: './Images/Cards/c7.jpg'},
  {id: 'c8', value: 8, suit: 'club', src: './Images/Cards/c8.jpg'},
  {id: 'c9', value: 9, suit: 'club', src: './Images/Cards/c9.jpg'},
  {id: 'ca', value: 10, suit: 'club', src: './Images/Cards/ca.jpg'},
  {id: 'cb', value: 11, suit: 'club', src: './Images/Cards/cb.jpg'},
  {id: 'cc', value: 12, suit: 'club', src: './Images/Cards/cc.jpg'},
  {id: 'd1', value: 1, suit: 'diamond', src: './Images/Cards/d1.jpg'},
  {id: 'd2', value: 2, suit: 'diamond', src: './Images/Cards/d2.jpg'},
  {id: 'd3', value: 3, suit: 'diamond', src: './Images/Cards/d3.jpg'},
  {id: 'd4', value: 4, suit: 'diamond', src: './Images/Cards/d4.jpg'},
  {id: 'd5', value: 5, suit: 'diamond', src: './Images/Cards/d5.jpg'},
  {id: 'd6', value: 6, suit: 'diamond', src: './Images/Cards/d6.jpg'},
  {id: 'd7', value: 7, suit: 'diamond', src: './Images/Cards/d7.jpg'},
  {id: 'd8', value: 8, suit: 'diamond', src: './Images/Cards/d8.jpg'},
  {id: 'd9', value: 9, suit: 'diamond', src: './Images/Cards/d9.jpg'},
  {id: 'da', value: 10, suit: 'diamond', src: './Images/Cards/da.jpg'},
  {id: 'db', value: 11, suit: 'diamond', src: './Images/Cards/db.jpg'},
  {id: 'dd', value: 12, suit: 'diamond', src: './Images/Cards/dc.jpg'},
  {id: 'h1', value: 1, suit: 'heart', src: './Images/Cards/h1.jpg'},
  {id: 'h2', value: 2, suit: 'heart', src: './Images/Cards/h2.jpg'},
  {id: 'h3', value: 3, suit: 'heart', src: './Images/Cards/h3.jpg'},
  {id: 'h4', value: 4, suit: 'heart', src: './Images/Cards/h4.jpg'},
  {id: 'h5', value: 5, suit: 'heart', src: './Images/Cards/h5.jpg'},
  {id: 'h6', value: 6, suit: 'heart', src: './Images/Cards/h6.jpg'},
  {id: 'h7', value: 7, suit: 'heart', src: './Images/Cards/h7.jpg'},
  {id: 'h8', value: 8, suit: 'heart', src: './Images/Cards/h8.jpg'},
  {id: 'h9', value: 9, suit: 'heart', src: './Images/Cards/h9.jpg'},
  {id: 'ha', value: 10, suit: 'heart', src: './Images/Cards/ha.jpg'},
  {id: 'hb', value: 11, suit: 'heart', src: './Images/Cards/hb.jpg'},
  {id: 'hb', value: 12, suit: 'heart', src: './Images/Cards/hb.jpg'},
  {id: 's1', value: 1, suit: 'spade', src: './Images/Cards/s1.jpg'},
  {id: 's2', value: 2, suit: 'spade', src: './Images/Cards/s2.jpg'},
  {id: 's3', value: 3, suit: 'spade', src: './Images/Cards/s3.jpg'},
  {id: 's4', value: 4, suit: 'spade', src: './Images/Cards/s4.jpg'},
  {id: 's5', value: 5, suit: 'spade', src: './Images/Cards/s5.jpg'},
  {id: 's6', value: 6, suit: 'spade', src: './Images/Cards/s6.jpg'},
  {id: 's7', value: 7, suit: 'spade', src: './Images/Cards/s7.jpg'},
  {id: 's8', value: 8, suit: 'spade', src: './Images/Cards/s8.jpg'},
  {id: 's9', value: 9, suit: 'spade', src: './Images/Cards/s9.jpg'},
  {id: 'sa', value: 10, suit: 'spade', src: './Images/Cards/sa.jpg'},
  {id: 'sb', value: 11, suit: 'spade', src: './Images/Cards/sb.jpg'},
  {id: 'sc', value: 12, suit: 'spade', src: './Images/Cards/sc.jpg'}
]

export const kings = [
  {id: 'cd', value: 12, suit: 'club', src: '../Images/Cards/cd.jpg'},
  {id: 'dd', value: 12, suit: 'diamond', src: '../Images/Cards/dd.jpg'},
  {id: 'sd', value: 12, suit: 'spade', src: '../Images/Cards/sd.jpg'},
  {id: 'hd', value: 12, suit: 'heart', src: '../Images/Cards/hd.jpg'}
]
