//IndexId, Menu Title, Description
export const listOfAchievements= [
  {id: 'gamesWon', title: 'Games Won', description: ''},
  {id: 'winPercentage', title: 'Win Percentage', description: ''},
  {id: 'threeInARowPercentage', title: 'King Killed by Same Value in a Row', description: ''},
  {id: 'fourInARowPercentage', title: 'King Killed by Suit', description: ''},
  {id: 'fiveInARowPercentage', title: 'King Killed by Alternating Color', description: ''},
  {id: 'currentWinStreak', title: 'Current Streak of Winning Games', description: ''},
  {id: 'totalWinStreak', title: 'Longest Streak of Winning Games', description: ''},
  {id: 'averageKingsKilled', title: 'Average Kings Killed', description: ''},
  {id: 'totalKingsKilled', title: 'Total Kings Killed', description: ''},
  {id: 'maximumCardsToKillKing', title: 'Maximum Cards Used in the Killing of a King', description: ''},
  {id: 10, title: 'Fewest Reserve Spots Used in a Win', description: ''},
  {id: 'renegade', title: 'Renegade', description: 'Killed All 4 Kings'},
  {id: 'revolutionary', title: 'Revolutionary', description: 'Won 5 Games'},
  {id: 'threvolution', title: 'Threvolution', description: 'Won 3 Games in a Row'},
  {id: 'sevenUp', title: 'Seven Up', description: 'Won 7 Games in a Row'},
  {id: 'bastilleMyHeart', title: 'Bastille My Heart', description: 'Won 14 games'},
  {id: 'tripleNinja', title: 'Triple Ninja', description: 'Killed All 4 Kings with the Same Value'},
  {id: 'suitedUp', title: 'Suited Up', description: 'Killed All 4 Kings with Same Suit'},
  {id: 'rainbowRebel', title: 'Rainbow Rebel', description: 'Killed All 4 Kings with Alternating Colors'},
  {id: 19, title: 'Clean Kill', description: 'Win Game with No Cards Left in Reserve Spots'},
  {id: 'patience', title: 'Patience', description: 'Used 14 or More Cards in the Killing of a King'},
  {id: 21, title: 'Show of Force', description: 'Killed All 4 Kings Only Using 4 Reserve Spots'},
  {id: 22, title: 'Far, Far Better', description: 'Only Used 1 Reserve at A Time'},
  {id: 23, title: 'Rabble Rouser', description: 'Followed Standard Games on Twitter'},
  {id: 24, title: 'Voice of the People', description: 'Tweeted A Victory'}
]
